function H=Algur2(trek)
T=0;
Tmax=30;
Ind=[];
trekIn=trek;
i=1;
Inds=[1:numel(trek)];
STSet=SpecialTreks(trek);
figure;
subplot(2,1,1);
plot(trek);
grid on; hold on;
subplot(2,1,2);
plot(std(trek),'.b');
grid on; hold on;
cm=colormap('lines');
timeId=tic;
while T<Tmax&&STSet.N>3;
    MaxTrek=interp1(STSet.MaxInd,trek(STSet.MaxInd),Inds,'spline','extrap');
    MinTrek=interp1(STSet.MinInd,trek(STSet.MinInd),Inds,'spline','extrap');
    trek=(MaxTrek+MinTrek)/2;
    trek=trek';
    i=i+1;
    subplot(2,1,1);
    plot(trek,'Color',cm(i,:));
    subplot(2,1,2);
    plot(i,std(trek),'.','Color',cm(i,:));
    plot(i,std(trekIn-trek),'*','Color',cm(i,:));
    STSet=SpecialTreks(trek);
    T=toc(timeId);
end;
H=trek;