function SXR_Sm=SXR_norm(SXR,Sm);
% figure;
%  plot(1:1714,SXR(:,2:15)); 
  SXR_Sm(:,1)=SXR(:,1);   
 for i=2:15 
        Null=mean(SXR(1:400,i));
        SXR(:,i)=SXR(:,i)-Null;
        SXRSm=smooth(SXR(:,i),Sm);
        Idx=find((SXR(:,i)-SXRSm)>std((SXR(:,i)-SXRSm)));
        SXR(Idx,i)=SXRSm(Idx);
        SXR_Sm(:,i)=smooth(SXR(:,i),Sm);
        SXR_Sm(:,i)=SXR_Sm(:,i)-min(SXR_Sm(400:1600,i));
        SXR_Sm(1:400,i)=0;
        SXR_Sm(1600:end,i)=0;
    end;
%         hold on;
%         plot(1:1714,SXR(:,2:15));
%         plot(1:1714,SXR_Sm(:,2:15));
%      figure;
%              plot(1:1714,SXR_Sm(:,2:15));
