set(gca,'FontSize',20)
set(gca,'FontWeight','demi')
title({'\parbox[b]{100mm}{\centering Wagner D. Convective cells}'...
    '\parbox[b]{100mm}{\centering $V_{rad}^{as\,V_x}/|V|,\delta V_{pol}^{as\,V_y}/|V|$}'...
    '\parbox[b]{100mm}{\centering Toroidal averaged. Time averaged in 90$\mu$s-180$\mu$s simulation time.}'...
    '\parbox[b]{100mm}{\centering $\delta V_{pol}= V_{pol}-<V_{pol}>^{flux\,surface\,avreaged}$}'},...
    'FontSize',24,'FontWeight','bold','Interpreter','latex');
ylabel('\Theta, grad/100','FontSize',20,'FontWeight','demi');
xlabel('r, cm','FontSize',20,'FontWeight','demi');